version: "3.7"

services:
    db:
        build:
            context: .
            dockerfile: ./docker/sql_docker/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: hej
        ports:
            - 3306:3306
    model:
        depends_on:
            - db
        build:
            context: .
            dockerfile: ./model/Dockerfile
        ports:
            - 8080:8080
    #vertx-data-service:
        #depends_on:
            #- db
        #image: vertx-data-service
        #ports:
            #- 8091:8091
    canvas:
        image: canvas
        ports:
            - 3000:3000
    ui:
        depends_on:
            - model
            - canvas
            #- vertx-data-service
        build:
            context: .
            dockerfile: ./ui/Dockerfile
        ports:
            - 8085:8080
